# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Mohit Reddy'
tagline:          ''
description:      '- Programmer, Night Owl.<br>- Current: SWE @Google Brain Frameworks and Infrastructure team.<br>- Past: SWE @GCE Control Plane Infrastructure team.<br>- Summer 2017 (May - August) Intern @Google, Search Infrastructure, Zurich.<br>'
url:              https://mohitreddy1996.github.io
baseurl:          /

author:
  name:           'Mohit Reddy'
  url:            'https://github.com/mohitreddy1996'

paginate:         5
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          2.1.0

# Collections.
collections:
  projects:
    output: true
  experiences:
    output: true

github:
repo:             https://github.com/mohitreddy1996/mohitreddy1996.github.io

twitter_username: MohitReddy13
github_username: mohitreddy1996
facebook_username: mohitreddy1996
googleplus_username: +MohitReddy1996
linkedin_username: mohit-reddy-334427104
emailid: mohitreddy1996@gmail.com
